backend:
  name: git-gateway
  branch: main  # Ensure this matches your main branch in the Git repo

media_folder: "resources/uploads"  # Where uploaded images for blog posts go
public_folder: "/resources/uploads"  # Public URL of uploaded images

collections:
  - name: "posts"
    label: "Blog Posts"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "post" } 
      - { label: "Titel", name: "title", widget: "string" }
      - { label: "Buch", name: "categories", widget: "string" }
      - { label: "Veröffentlichungsdatum", name: "date", widget: "datetime", format: "YYYY-MM-DDTHH:mm:ss", picker_utc: true, default: "now" }
      - { label: "Text", name: "body", widget: "markdown" }
      - { label: "PDF (Verlinkt)", name: "pdf", widget: "file", required: false }
      - { label: "PDF Link-Text", name: "pdftitle", widget: "string", required: false }
      - { label: "Audio", name: "audio", widget: "file", required: false }
      - { label: "Video", name: "video", widget: "file", required: false }
  - name: "books"
    label: "Bücher"
    folder: "_books"
    create: false
    slug: "{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "book" } 
      - { label: "Titel", name: "title", widget: "string" }
      - { label: "Erstellungsdatum", name: "date", widget: "datetime", format: "YYYY-MM-DDTHH:mm:ss", picker_utc: true, default: "now" }
      - { label: "Buch", name: "categories", widget: "string" }
      - { label: "Autoren", name: "authors", widget: "string" }
      - { label: "Autoren Kurz", name: "authors-short", widget: "string" }
      - { label: "Kurzbeschreibung", name: "shorttext", widget: "string" }
      - { label: "Veröffentlichungsdatum", name: "published", widget: "string" }
      - { label: "Vorschau-PDF", name: "vorschau-pdf", widget: "file", required: false }
      - { label: "Shop-Link", name: "shoplink", widget: "string", required: false }
      - { label: "Text", name: "body", widget: "markdown" }
      - { label: "Cover", name: "image", widget: "image", required: true }
      - { label: "Hintergrundbild/Coverbild", name: "backimage",  widget: "image", required: true }
  - name: "pages"
    label: "Pages"
    files:
      - label: "Sefiroth"
        name: "sefiroth"
        file: "sefiroth.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Text", name: "body", widget: "markdown" }
          - { label: "PDF (Verlinkt)", name: "pdf", widget: "file", required: false }
          - { label: "PDF Link-Text", name: "pdftitle", widget: "string", required: false }
      - label: "Reihe"
        name: "reihe"
        file: "reihe.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Text", name: "body", widget: "markdown" }
      - label: "Home"
        name: "home"
        file: "index.md"
        fields:
          - { label: "Text", name: "body", widget: "markdown" }
      - label: "Impressum"
        name: "impressum"
        file: "impressum.md"
        fields:
          - { label: "Text", name: "body", widget: "markdown" }
      - label: "Beirat"
        name: "beirat"
        file: "beirat.md"
        fields:
          - { label: "Text", name: "body", widget: "markdown" }
