backend:
  name: git-gateway
  branch: main  # Ensure this matches your main branch in the Git repo

media_folder: "resources/images"  # Where uploaded images for blog posts go
public_folder: "/resources/images"  # Public URL of uploaded images

collections:
  - name: "posts"
    label: "Blog Posts"
    folder: "_posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "post" } 
      - { label: "Titel", name: "title", widget: "string" }
      - { label: "Buch", name: "categories", widget: "string" }
      - { label: "Veröffentlichungsdatum", name: "date", widget: "datetime", format: "YYYY-MM-DDTHH:mm:ss", picker_utc: true, default: "now" }
      - { label: "Text", name: "body", widget: "markdown" }
      - { label: "Bild", name: "image", widget: "image", required: false }
